services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tayyar
    ports:
      - "4000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development